name: .NET BUILD PACKAGE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x     
    - name: Install Java 11
      uses: actions/setup-java@v1
      with: 
        java-version: '11'        
    - name: Install SonarScanner
      run: dotnet tool install dotnet-sonarscanner --global
    - name: Restore dependencies
      run: dotnet restore
    - name: Sonar Begin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet-sonarscanner begin /k:"YulerB_K8-TCP-Probe" /o:"yulerb" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths=**/*.trx /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml /v:1.0.1.${{ github.run_number }} /d:sonar.links.ci=https://github.com/YulerB/k8-tcp-probe/actions/runs/${{ github.run_id }} /d:sonar.links.scm=https://github.com/YulerB/k8-tcp-probe
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Sonar End
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}" 
    - name: Pack
      run: dotnet pack --configuration Release
    - name: PushNuget
      run: dotnet nuget push "bin/Release/K8-TCP-Probe.1.0.7.nupkg"  --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"  --skip-duplicate
    - name: PushGit
      run: dotnet nuget push "bin/Release/K8-TCP-Probe.1.0.7.nupkg" --api-key ${GITHUB_TOKEN} --source "https://nuget.pkg.github.com/K8-TCP-Probe/index.json"   --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
