name: .NET NUGET PACKAGE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore k8-tcp-probe.sln
    - name: Build
      working-directory: src
      run: dotnet build k8-tcp-probe.sln --no-restore --configuration Release
