name: .NET NUGET PACKAGE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore k8-tcp-probe.sln
    - name: Build
      working-directory: src
      run: dotnet build k8-tcp-probe.sln --no-restore --configuration Release
