name: .NET NUGET PACKAGE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  strategy:
    matrix:
      configuration: [8.0.x]

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.configuration }}
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
      with:
        dotnet-version: ${{ matrix.configuration }}
    