name: .NET BUILD PACKAGE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x     
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release
    - name: PushNuget
      run: dotnet nuget push "bin/Release/K8-TCP-Probe.1.0.7.nupkg"  --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"  --skip-duplicate
    - name: PushGit
      run: dotnet nuget push "bin/Release/K8-TCP-Probe.1.0.7.nupkg" --api-key ${GITHUB_TOKEN} --source "https://nuget.pkg.github.com/K8-TCP-Probe/index.json"   --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
